export const manual='https://damcdn.demant.com/bacb105f-2d5d-4db9-9c56-ace000c8886d/227098NL_IFU_Opn_S_Opn_Play_Opn_Siya_Ruby_BTE_BTE_PP_MDR_Original%20file.pdf';
// Page references are printed page numbers in the manufacturer manual.
const s=(title,text,mode='normal',note='')=>({title,text,mode,note});
export const lessons={
 kennen:{title:'Leer de onderdelen kennen',icon:'◉',desc:'Wat is wat?',pages:'12–17',steps:[s('Dit is het oefentoestel','Het grote deel hangt achter uw oor. Het vangt geluid op en versterkt het.','body','Schematisch 3D-model. De vorm van uw eigen toestel kan anders zijn.'),s('De haak en het slangetje','Het geluid gaat door de haak en het holle slangetje naar uw oor.','tube'),s('Het harde oorstukje','Dit is op maat gemaakt. Het past in uw oor en houdt het slangetje op zijn plek.','mold'),s('De batterijlade','Hier zit de batterij. Met deze lade zet u het toestel aan en uit.','open'),s('De dubbele knop','Met deze knop kunt u soms het volume of programma veranderen. Uw audicien bepaalt welke functies werken.','button'),s('De microfoons','De kleine openingen vangen geluid op. Houd ze vrij en schoon. Steek er niets in.','mic')]},
 aan:{title:'Aan en uit zetten',icon:'⏻',desc:'Met de batterijlade',pages:'18, 44–45',steps:[s('Aan: sluit de lade','Sluit de batterijlade voorzichtig. Er moet een goede batterij in zitten. Het toestel start vanzelf.','closed'),s('Uit: open de lade','Open de batterijlade met uw nagel bij het lipje. Het toestel gaat uit.','open','Gaat de lade niet makkelijk open? Niet forceren. Een kindveilige lade vraagt een speciale aanpak van uw audicien.'),s('Voor de nacht','Doe het toestel uit uw oor. Laat de batterijlade open op een droge, veilige plek.','open','Buiten bereik van kinderen en huisdieren. Gebruik dempen niet als uitknop.')]},
 dragen:{title:'Indoen en uitdoen',icon:'↗',desc:'Eerst het oorstukje',pages:'16, 22; Oticon: indoen en uitdoen',steps:[s('Kies het juiste oor','Blauw hoort bij LINKS. Rood hoort bij RECHTS. Kijk in de batterijlade of op het oorstukje.','sides','De kleur van de hele behuizing vertelt u niet welk oor het is.'),s('Pak het oorstukje vast','Houd het harde oorstukje vast. De bocht van het slangetje wijst naar boven.','mold'),s('Plaats het oorstukje','Trek uw oor zo nodig zacht naar buiten. Plaats het oorstukje voorzichtig met een lichte draaibeweging.','insert','Het mag geen pijn doen. Duw niet door als het niet past.'),s('Leg het toestel achter uw oor','Leg de behuizing achter uw oor. Controleer of het slangetje zonder knik loopt.','wear'),s('Uitdoen: eerst achter uw oor','Til de behuizing van uw oor. Laat deze voorzichtig voor uw oor hangen.','remove'),s('Haal het oorstukje eruit','Pak het harde oorstukje vast. Haal het voorzichtig uit uw oor, eventueel met een kleine draaibeweging.','mold','Trek niet aan het slangetje.')]},
 batterij:{title:'Batterij vervangen',icon:'+',desc:'Rustig, met een wachttimer',pages:'19–21, 56',steps:[s('Werk boven een tafel','Leg een zachte doek neer. Pak een nieuwe zink-luchtbatterij maat 13.','battery','Maat 13 geldt voor de modellen in deze handleiding. Controleer het type op uw verpakking of bij uw audicien. Niet opladen.'),s('Haal de oude batterij eruit','Open de lade helemaal en neem de oude batterij eruit.','batteryout','Houd batterijen weg van kinderen, huisdieren en medicijnen.'),s('Trek de sticker eraf','Verwijder de sticker van de nieuwe batterij.','batteryout'),s('Wacht 2 minuten','Laat de batterij lucht opnemen. Start hieronder de timer.','timer','Wacht ook als u de timer niet gebruikt.'),s('Plaats de batterij','Leg de batterij van bovenaf in de lade. De platte kant met het plusteken komt naar boven, zoals in de handleiding.','batteryin','Schuif de batterij niet vanaf de zijkant in de lade.'),s('Sluit de lade voorzichtig','De lade moet makkelijk sluiten. Het toestel start en kan een melodietje geven.','closed','Past het niet? Open de lade en controleer de batterij. Gebruik geen kracht. Lever de oude batterij in bij een inzamelpunt.')]},
 schoon:{title:'Dagelijks schoonmaken',icon:'✧',desc:'Droog en voorzichtig',pages:'23–25',steps:[s('Zet het toestel uit','Doe het toestel uit uw oor en open de batterijlade. Werk boven een zachte doek, met schone en droge handen.','open'),s('Veeg de behuizing af','Gebruik een zachte, droge doek.','body','Het elektronische toestel nooit wassen of onderdompelen. Geen alcohol of schoonmaakmiddelen gebruiken.'),s('Borstel de openingen zacht','Verwijder vuil voorzichtig met het meegeleverde borsteltje. Borstel over de microfoonopeningen.','mic','Duw geen borstelharen of voorwerpen in de openingen.'),s('Veeg het oorstukje af','Maak het harde oorstukje droog schoon. Verwijder zichtbaar oorsmeer voorzichtig bij de opening met het daarvoor bedoelde gereedschap.','mold','Gebruik het gereedschap nooit in uw oor. Zit vuil vast of wordt de slang hard of geel? Vraag uw audicien.')]},
 wassen:{title:'Het harde oorstukje wassen',icon:'≈',desc:'Alleen het losse oorstukje en de slang',pages:'24–25',steps:[s('Controleer eerst het type','Deze wasstappen zijn alleen voor een hard oorstukje met een hol, dik slangetje en een haak.','mold','Bij een dun slangetje, draadje of luidsprekertje in het oor gelden andere stappen. Niet wassen zolang het type onbekend is.'),s('Werk met één toestel tegelijk','Zo verwisselt u links en rechts niet. Zet het toestel uit.','open'),s('Maak de slang los van de haak','Houd de haak stevig vast. Trek het slangetje voorzichtig van de haak af.','detach','Laat de haak aan de behuizing zitten. Vraag hulp als het vastzit.'),s('Was alleen het losse deel','Was het losse oorstukje en slangetje met milde zeep. Spoel goed af.','wash','Houd de elektronische behuizing ver van het water.'),s('Laat alles volledig drogen','Ook binnen in het slangetje mag geen water meer zitten.','detach','Gebruik geen föhn, oven of verwarming. Een speciale blaasbalg kan helpen; vraag uw audicien.'),s('Zet de droge slang terug','Schuif het slangetje weer op de haak. Controleer of alles goed vastzit.','normal')]},
 knoppen:{title:'Volume, programma en dempen',icon:'±',desc:'Alleen als ingesteld',pages:'33–38, 76–81',optional:true,steps:[s('Controleer uw eigen instellingen','Vraag uw audicien welke knoppen werken. De volgende voorbeelden gelden alleen als deze functies zijn ingesteld.','button'),s('Harder of zachter','Bij volumebediening: druk kort bovenaan voor harder. Druk kort onderaan voor zachter. U hoort een klik.','volume','De instelling kan over beide toestellen worden verdeeld. Volg altijd uw persoonlijke afspraken.'),s('Een ander luisterprogramma','Uw toestel kan maximaal 4 programma’s hebben. Vraag welke drukhandeling u moet gebruiken en waarvoor elk programma is bedoeld.','button','Er is geen universele drukduur voor alle persoonlijke instellingen. 1 tot 4 tonen kunnen het gekozen programma aangeven.'),s('Tijdelijk dempen','Als dempen is ingeschakeld: houd één kant van de knop 4 seconden ingedrukt. Druk kort om weer te horen.','mute','Dit dempt de microfoons. Streaming of tinnitusgeluid kan blijven werken. Het toestel verbruikt nog batterij.'),s('Terug naar de begininstelling','Open en sluit de batterijlade. Het toestel start met de ingestelde beginwaarden.','closed')]},
 nat:{title:'Het toestel is nat',icon:'≈',desc:'Veilig laten drogen',pages:'58, 64',steps:[s('Veeg het water weg','Dep het toestel voorzichtig droog met een zachte doek.','body'),s('Haal de batterij eruit','Open de lade. Verwijder de batterij en dep zichtbaar water in de lade voorzichtig weg.','batteryout'),s('Laat het drogen','Laat het toestel ongeveer 30 minuten liggen met de lade open, zoals de fabrikant beschrijft.','open','Geen föhn of andere hitte. Is het nog vochtig? Niet opnieuw inschakelen; vraag uw audicien.'),s('Probeer een nieuwe batterij','Plaats pas als het toestel droog is een nieuwe batterij. Werkt het niet goed? Neem contact op met uw audicien.','closed','Doe uw toestel altijd uit voor douchen, zwemmen of andere wateractiviteiten. IP68 betekent niet dat u ermee mag zwemmen.')]},
 vliegtuig:{title:'In het vliegtuig',icon:'✈',desc:'Bluetooth uitschakelen',pages:'32, 59',optional:true,steps:[s('Volg de aanwijzingen aan boord','Voor de modellen in deze handleiding kunt u Bluetooth uitschakelen met vliegtuigmodus. Het horen blijft werken.','normal'),s('Houd de knop minstens 7 seconden vast','Druk op één uiteinde van de dubbele knop. Een melodietje bevestigt vliegtuigmodus. Bij gekoppelde toestellen werkt dit voor beide.','button'),s('Vliegtuigmodus weer uit','Open en sluit de batterijlade, of houd de knop opnieuw minstens 7 seconden ingedrukt.','closed','Controleer eerst of Bluetooth weer gebruikt mag worden.')]}
};
export const faqs=[
['Ik hoor niets. Wat nu?','Controleer of de lade dicht is en de batterij goed zit. Open en sluit de lade om dempen en tijdelijke instellingen te herstellen. Probeer een nieuwe batterij. Controleer het oorstukje op vuil. Blijft het stil? Vraag uw audicien.'],
['Het toestel fluit. Wat doe ik?','Controleer of het oorstukje goed in uw oor zit. Blijft het fluiten, laat de pasvorm en mogelijk oorsmeer door uw audicien of arts beoordelen. Steek niets in uw oor.'],
['Wat betekenen drie tonen?','Drie afwisselende tonen die later terugkomen wijzen op een bijna lege batterij. Drie korte tonen tijdens het regelen kunnen ook de hoogste of laagste volumestand aangeven. De context is dus belangrijk.'],
['Wat betekenen vier dalende tonen?','De batterij is leeg. Vervang de batterij.'],
['Ik hoor acht piepjes, vier keer achter elkaar.','De handleiding noemt dit een signaal voor controle van de microfoons. Neem contact op met uw audicien. Een bijbehorend rood lampje bestaat alleen op bepaalde uitvoeringen.'],
['Waarom werkt Bluetooth ineens niet?','Bij een bijna lege batterij wordt Bluetooth uitgeschakeld. Probeer een nieuwe batterij en controleer vliegtuigmodus. Ook koppeling en telefooncompatibiliteit kunnen een oorzaak zijn.'],
['Moet er een lampje branden?','Nee. Niet elk model heeft een lampje. Een ontbrekend lampje betekent niet automatisch dat uw toestel kapot is.'],
['Mag ik ermee slapen of douchen?','Doe het toestel voor het slapen uit en laat de lade open. Doe het uit voor douchen, zwemmen en andere wateractiviteiten.'],
['Het oorstukje doet pijn.','Haal het toestel uit. Duw het oorstukje niet verder. Laat de pasvorm controleren. Bespreek pijn, huidirritatie of vocht uit het oor met uw audicien of arts.'],
['Er zit een dopje vast in mijn oor.','Probeer het niet zelf met een pincet of ander voorwerp weg te halen. Neem contact op met een zorgprofessional.'],
['Er is mogelijk een batterij ingeslikt.','Zoek onmiddellijk medische hulp. Wacht niet op klachten. Vertel dat het om een knoopcelbatterij gaat.'],
['Mag iemand anders mijn toestel proberen?','Het toestel is persoonlijk ingesteld op uw gehoor. Laat het door de audicien aanpassen voordat een ander het gebruikt.']
];
